# 内部CA用Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca
  namespace: cert-manager
spec:
  secretName: ca-key-pair
  isCA: true
  commonName: k8s-myhome-internal-ca
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
