apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-selfsigned-issuer.yaml
  - cert-manager-internal-ca-issuer.yaml
  - cert-manager-internal-ca-certificate.yaml
  - cert-manager-letsencrypt-cloudflare-issuer.yaml
  - cert-manager-letsencrypt-cloudflare-staging-issuer.yaml
  - wildcard-external-cert.yaml
  - wildcard-internal-cert.yaml
