apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-ca-cert
  namespace: arc-systems
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDDzCCAfegAwIBAgIRAJEcs6z5gMzqrbaja2AlI0IwDQYJKoZIhvcNAQELBQAw
    ITEfMB0GA1UEAxMWazhzLW15aG9tZS1pbnRlcm5hbC1jYTAeFw0yNjAxMjQwODI2
    NDVaFw0yNjA0MjQwODI2NDVaMCExHzAdBgNVBAMTFms4cy1teWhvbWUtaW50ZXJu
    YWwtY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvkbRy30AkGO1A
    tmi5Ob/cWkgimrVB4YiOhboXPtEus1mm4xcsv/2yKTrssvs+6tB7EYcXt7+OP1+6
    ACt5IeIn+LwqJUTCGpczVD3LXKT3PRzPRutAmHUUez2qVLsgAjWqO6I5ocJfYXBq
    4EYD1+sbDE8bWZVRJKn6meW1j9YF5ouG9gF8DJ5HgjBryQicrh+4BMttHLEz5NUp
    lOHYYJLPlsme8OWoOjGWdskHIOlTabYy0koe21M/x87IVy1LbArSuLkU0LPbniPb
    vAb4OLPtiRDa+OVd7k1lJqyKMIr0uJIbKe0xcq4Mog0IeZf6YEq2P/d7FIAKAsrI
    vymSsUpxAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/
    MB0GA1UdDgQWBBRpMUDhZ0hFijnq4tTe3EtIKcpcjTANBgkqhkiG9w0BAQsFAAOC
    AQEAnaKyjZkAUMZI5F83hz+2Ig/w2JCs9idakScswlbONafy0ki97ah28Xfwj0/A
    2tZWoPJ/lhySj94ibjPQmbDI/VsmmrjXM3Jfo0zeKtaaxwYq1fbQ7cbuXdVeEtzZ
    skXYqWM2rydX5E/H5wfaizkv2BgIfQcJgBxShiLf5e4LGL7VyWiXt1CXO+xI2BIY
    /a26ggg+kkQRASbswrl5PhxtWlfb7j9QCpw9NxNgIB8WpEYB3zIgzzYMD5YLXlxF
    Az/H5e/nEatM5LcEF0I0uOHhkvd/E0GWVbhIxS6GA6aIWXg77AtQ5Vpx3I2uIud4
    r+hKSPC/NyK2Jk29NFKEsrjnmg==
    -----END CERTIFICATE-----
