apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: blog-image-updater
  namespace: argocd
spec:
  namespace: argocd
  writeBackConfig:
    method: git:secret:argocd/git-creds
    gitConfig:
      branch: main
      writeBackTarget: kustomization:.
  applicationRefs:
    - namePattern: "blog"
      images:
        - alias: blog
          imageName: harbor.qroksera.com/sandbox/blog
          commonUpdateSettings:
            updateStrategy: semver
            allowTags: "regexp:^\\d+\\.\\d+\\.\\d+$"
            pullSecret: pullsecret:argocd/harbor-registry
          manifestTargets:
            kustomize:
              name: harbor.qroksera.com/sandbox/blog
