apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifest.yaml
  - image-updater.yaml
images:
  - name: harbor.qroksera.com/sandbox/slack.rs
    newTag: 0.0.7
    newName: harbor.qroksera.com/sandbox/slack.rs
