apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https-argocd-external
      hostname: argocd.qroksera.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: wildcard-external-tls
            namespace: nginx-gateway
      allowedRoutes:
        namespaces:
          from: All
    - name: https-rustfs
      hostname: rustfs.qroksera.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: wildcard-external-tls
            namespace: nginx-gateway
      allowedRoutes:
        namespaces:
          from: All
    - name: https-harbor-external
      hostname: harbor.qroksera.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: wildcard-external-tls
            namespace: nginx-gateway
      allowedRoutes:
        namespaces:
          from: All
    - name: https-internal
      hostname: "*.internal.qroksera.com"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: wildcard-internal-tls
            namespace: nginx-gateway
      allowedRoutes:
        namespaces:
          from: All
