apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https-argocd-external
      hostname: argocd.qroksera.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: qroksera-wildcard-tls
            namespace: nginx-gateway
      allowedRoutes:
        namespaces:
          from: All
    - name: https-argocd-internal
      hostname: argocd.internal.qroksera.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: argocd-internal-tls
            namespace: argocd
      allowedRoutes:
        namespaces:
          from: All
    - name: https-rustfs
      hostname: rustfs.qroksera.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: qroksera-wildcard-tls
            namespace: nginx-gateway
      allowedRoutes:
        namespaces:
          from: All
    - name: https-harbor-external
      hostname: harbor.qroksera.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: qroksera-wildcard-tls
            namespace: nginx-gateway
      allowedRoutes:
        namespaces:
          from: All
    - name: https-harbor-internal
      hostname: harbor.internal.qroksera.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: harbor-internal-tls
            namespace: harbor
      allowedRoutes:
        namespaces:
          from: All
