apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: argocd-external-tls
            namespace: argocd
          - kind: Secret
            name: argocd-internal-tls
            namespace: argocd
          - kind: Secret
            name: rustfs-external-tls
            namespace: rustfs
          - kind: Secret
            name: harbor-external-tls
            namespace: harbor
          - kind: Secret
            name: harbor-internal-tls
            namespace: harbor
      allowedRoutes:
        namespaces:
          from: All
