# 内部公開用ワイルドカード証明書
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-internal
  namespace: nginx-gateway
spec:
  secretName: wildcard-internal-tls
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.internal.qroksera.com"
  usages:
    - digital signature
    - key encipherment
    - server auth
