apiVersion: batch/v1
kind: CronJob
metadata:
  name: rss-monitor-cronjob
  namespace: sandbox
spec:
  schedule: "0 8 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: rss-monitor
        spec:
          containers:
            - name: rss-monitor
              image: harbor.qroksera.com/sandbox/rss:latest
              imagePullPolicy: Always
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: slack
                      key: SLACK_BOT_TOKEN
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: tidb
                      key: uri
          imagePullSecrets:
            - name: harbor-registry
          restartPolicy: OnFailure
