# Tailscale サブネットルータ（k8s内部ネットワーク公開）
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: k8s-subnet-router
spec:
  replicas: 1
  hostnamePrefix: k8s-subnet-router
  tags:
    - tag:k8s-subnet-router
  subnetRouter:
    advertiseRoutes:
      - "192.168.122.0/24"
