apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Gateway API CRD（NGF v2.3.0 標準チャネル）
  - https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v2.3.0
