# Harbor外部公開用TLS証明書
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-external-cert
  namespace: harbor
spec:
  secretName: harbor-external-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - harbor.qroksera.com
  usages:
    - digital signature
    - key encipherment
    - server auth
