apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-auth
  namespace: arc-systems
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: pulumi-esc-store
    kind: ClusterSecretStore
  target:
    name: harbor-auth
    creationPolicy: Owner
  data:
  - secretKey: HARBOR_URL
    remoteRef:
      key: harbor
      property: url
  - secretKey: HARBOR_USERNAME
    remoteRef:
      key: harbor
      property: username
  - secretKey: HARBOR_PASSWORD
    remoteRef:
      key: harbor
      property: password
