apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pulumi-esc-secretstore.yaml  # 最初にClusterSecretStore
  - argocd-github-oauth-secret.yaml  # 次にArgoCD用
  - external-secret-resources.yaml  # まとめ定義
  - grafana-cloud-external-secret.yaml
  - grafana-monitoring-external-secret.yaml
