apiVersion: batch/v1
kind: CronJob
metadata:
  name: hitomi-monitor
  namespace: sandbox
spec:
  schedule: "55 13 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: hitomi-monitor
        spec:
          containers:
            - name: hitomi-monitor
              image: harbor.qroksera.com/sandbox/hitomi:0.0.2
              imagePullPolicy: Always
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: slack
                      key: SLACK_BOT_TOKEN
                - name: RUST_LOG
                  value: "INFO"
                - name: LOG_LEVEL
                  value: "INFO"
                - name: SELENIUM_COMMAND_EXECUTOR
                  value: http://selenium-standalone-chrome.tools:4444/wd/hub
          restartPolicy: Never
          imagePullSecrets:
            - name: harbor-registry
